version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: achatdb   
    ports:
      - 3306:3306
    networks:
     - projectdevops
     
  spring-boot:
    image: achatProject/image:1.0
    container_name: springcontainer
    ports:
      - 8095:8095
    depends_on:
      - database
    networks:
      - projectdevops 
    restart: on-failure     
 
  
networks:
  projectdevops:
     